### ISSUE TITLE
How to get launch URL after the execution completed in jenkins instance

### ISSUE THREAD

**Issue by preetipadalia** [reportportal/agent-net-gauge#48]
Hi,

Is it possible to get the launch URL where the report get pushed in ReportPortal?

Thanks
Preeti

**Comment by nvborisenko** [comment]
@preetipadalia what if plugin will output the url into standard console (like you see `Finishing to send results into Report Portal...`)? Does it resolve your request?

**Comment by preetipadalia** [comment]
Yes this may help.

**Comment by rahulbhaviri** [comment]
Continuing this discussion and also in respect to #34, 
@nvborisenko is there a way I can call the plugin and get the log mentioned above? I know it prints in the console; so can we make a call to the plugin and get that Launch ID programatically, so that I can reuse it?
Or will the launch ID be available in any binary files where my run is done? so that I can grep it from the file?
Does using report portal client instead of plugin solve this problem?

My use case is that I need to get the launch ID so that I can get all the data associated with it by making API calls; even if all the meta data is not available, can we just get the launch ID from any of the above approaches?

**Comment by nvborisenko** [comment]
Action items to resolve this issue:
- Print out URL to the launch in console output.
- Put launch id into some file in `logs` folder, let's say file name is `ReportPortal.Launch.Uuid`

**Comment by mathew-jithinm** [comment]
@nvborisenko It will be really great if you can share a new build with the changes?

**Comment by nvborisenko** [comment]
@mathew-jithinm take it here https://github.com/reportportal/agent-net-gauge/releases/tag/1.13.1

**Comment by mathew-jithinm** [comment]
Thanks a lot @nvborisenko for the help.

**Comment by mathew-jithinm** [comment]
<img width="915" alt="Screenshot 2022-07-12 at 6 31 24 PM" src="https://user-images.githubusercontent.com/94165278/178496222-dbb66387-909a-46a0-9f96-25b481e9ff67.png">

I am unable to get the launch id log file in my case @nvborisenko Getting the attached ones. Can you please help here?

**Comment by nvborisenko** [comment]
Please share content of `ReportPortal.GaugePlugin.log`

**Comment by mathew-jithinm** [comment]
@nvborisenko Just tried and when we use the latest version of Gauge plugin and Gauge Java, the file is getting generated. Is there any dependency on the same?

**Comment by nvborisenko** [comment]
This functionality is available in v1.13.1
https://github.com/reportportal/agent-net-gauge/releases/tag/1.13.1

**Comment by rahulbhaviri** [comment]
Hey @nvborisenko did we remove this functionality in the new version as we are getting an error in finding the file ReportPortal.Launch.Uuid

**Comment by nvborisenko** [comment]
Fixed in 1.14.1
